### ISSUE TITLE
Close this repo

### ISSUE THREAD

**Issue by n0omad** [ImanAski/itsacliche#2]
Hey there developer,

Please consider closing this repo as it does not serve any purpose anymore.

Regards

**Comment by ImanAski** [comment]
Sorry, fellow developer. Take a look at other repos. Notify me if any of them serve a single purpose of meaning. Happy Coding :)

**Comment by n0omad** [comment]
https://github.com/n0omad/dotfiles/commit/3655e8443fafb67a2826fc94291ceeb01ae709ac#commitcomment-95431614

So isn't there any meanings in this beautiful blog either?

**Comment by ImanAski** [comment]
Got me there :)
